# Generated by Django 4.0.4 on 2022-05-27 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_group_course_group_course_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_main', models.CharField(max_length=255, verbose_name='Вариант')),
                ('option_secondary', models.CharField(max_length=255, verbose_name='Дополнительный вариант')),
                ('is_answer', models.BooleanField(verbose_name='Является ли ответом?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='backend.question')),
            ],
            options={
                'verbose_name': 'Вариант вопроса',
                'verbose_name_plural': 'Варианты вопроса',
            },
        ),
        migrations.CreateModel(
            name='TestPassResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='backend.student')),
            ],
            managers=[
                ('results', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='test',
            name='created',
        ),
        migrations.RemoveField(
            model_name='test',
            name='updated',
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_ones', to='backend.test')),
            ],
            options={
                'ordering': ['test__id'],
            },
        ),
        migrations.CreateModel(
            name='TestPassResultOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.questionoption')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.testquestion')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result_ones', to='backend.testpassresult')),
            ],
        ),
        migrations.AddField(
            model_name='testpassresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.test'),
        ),
    ]
